---
title: "analysis"
author: "Johannes Nakayama"
date: "3 12 2019"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggraph)
library(igraph)
library(stats)

library(plot3Drgl)
library(viridis)
library(dplyr)
library(gganimate)

```

```{r Data Import}

simruns <- list.files("dataexchange")[1]


for (i in 1:length(simruns)) {
   assign(paste0(simruns[i], "_sim_df"), read.csv(file.path("dataexchange", simruns[i], "sim_df.csv")))
   assign(paste0(simruns[i], "_post_df"), read.csv(file.path("dataexchange", simruns[i], "post_df.csv")))
   for (j in 0:10) {
     assign(paste0(simruns[i], "_graph_", j), read_graph(file.path("dataexchange", simruns[i], paste0("graph_", j+1, ".gml")), format = "gml"))
   }
    
}

# ggraph(feed_length_run1_graph_10) + geom_edge_link() + geom_node_point() + theme_graph()


# length(V(xmasbatchtest_run1_graph_10))/length(V(xmasbatchtest_run1_graph_0))


```

```{r}

head(data)

```


```{r}

feed_length_run4 %>% 
  select(TickNr, Opinion) %>% 
  group_by(TickNr) %>% 
  summarize(MeanOpinion = mean(Opinion)) %>% 
  ggplot(aes(x=TickNr, y=MeanOpinion)) +
  geom_line(color='red') + 
  theme_bw()

ggsave(filename='opinion_development.png')

```


```{r}

feed_length_run4 %>% 
  select(TickNr, PerceivPublOpinion) %>% 
  group_by(TickNr) %>% 
  summarize(MeanPerceivPublOpinion = mean(PerceivPublOpinion)) %>% 
  ggplot(aes(x=TickNr, y=MeanPerceivPublOpinion)) +
  geom_line(color='red') + 
  theme_bw()

```


```{r}

data %>% 
  select(TickNr, Indegree) %>% 
  group_by(TickNr) %>% 
  summarize(MeanFollowers = mean(Indegree)) %>% 
  ggplot(aes(x=TickNr, y=MeanFollowers)) +
  geom_line(color='red') + 
  theme_bw()

```


```{r}

data %>% 
  filter(AgentID == 3) %>%
  ggplot(aes(x=TickNr, y=Opinion, color=ActiveStatus)) +
  geom_line() +
  theme_bw()

ggsave(filename='specific_agent_2.png')

```

```{r}

data %>% 
  filter(AgentID == 17) %>%
  ggplot(aes(x=TickNr, y=Opinion, color=ActiveStatus)) +
  geom_line() +
  theme_bw()

```

```{r}

data %>% 
  ggplot(aes(x=InclinInteract)) +
  geom_histogram(alpha=0.5, aes(y=..density..)) +
  geom_density(fill='blue', alpha=0.2) +
  theme_bw()

```

```{r}

data %>% 
  ggplot(aes(x=InclinInteract, y=Opinion)) +
  geom_point(alpha=0.2)

```



```{r}

theme_set(theme_bw())

data2$AgentID <- as.factor(data2$AgentID)

data2 %>%  
  filter(ActiveStatus == 'true') %>% 
  ggplot(aes(x=TickNr, y=Opinion, color=AgentID)) +
  geom_line(alpha=0.2) +
  theme(legend.position = "none") +
  NULL

```


```{r}

# Prepare for 3D Histogram
viewpoint <- matrix(c(0.581680357,	-0.813347518,	-0.010670132,	27.88446792,
                      0.311022758,	0.210274488,	0.926849186,	41.81242048,
                      -0.751606762,	-0.54244858,	0.375282109,	-2.694485856,
                      0, 0, 0, 1), nrow = 4, byrow = TRUE)

# Build Array of Histograms

for (runname in simruns){
  
  df <- get(paste0(runname, "_sim_df"))
  
  seq(-1,1, by=0.1) %>%
    round(digits=1) %>%
    table() -> histarray


  for (i in 1:max(df$TickNr)){
    
    if (i %% ceiling(max(df$TickNr) / 10) == 0 ) cat(paste0(round(i / max(df$TickNr) * 100), '% --- '))
    df %>%
        filter(.$TickNr == i, .$ActiveState == "true") %>%
        .[,3] %>%
        round(digits=1) %>%
        table() %>%
        bind_rows(histarray,.) -> histarray
    
    if (i == max(df$TickNr)) cat(': Done')
  }
  
  histarray[is.na(histarray)] <- 0
  histarray %>%
      .[-1,] %>%
      as.matrix() -> histarraymatrix
  
  assign(paste0(runname, "histarraymatrix"), histarraymatrix)
  
  # Build the 3D Histogram
  persp3Drgl(
      x=1:nrow(histarraymatrix), y = seq(-1,1, by=0.1),
          contour=FALSE, z = histarraymatrix,
          box=FALSE, shade=0.1,
          xlab="", ylab="", zlab="",
          col=viridis(n=2000, direction = -1), colkey=FALSE, axes=FALSE
      )
  
  
  # Formatting the Output
  view3d(userMatrix=viewpoint, zoom=0.6)
  par3d(windowRect = c(405, 104, 1795, 984))
  aspect3d(x=1.4,y=1.2,z=0.5)
  bbox3d(color=c("#EEEEEE","#AAAAAA"), xlen = 0, ylen = 0, zlen = 0)
  grid3d(side="x++", col="white", lwd=2)
  grid3d(side="y++", col="white", lwd=2)
  grid3d(side="z--", col="white", lwd=2)
  axis3d('x--', at = seq(0,floor(max(df$TickNr)/200)*200, by=200))
  axis3d('y--')
  axis3d('z-+', at = seq(0,floor(max(histarraymatrix)/500)*500, by=500))
  mtext3d("Simulation Step", "x--", line=2)
  mtext3d("Opinion", "y--", line=2)
  mtext3d("Agent Count", "z-+", line=2)
  
  snapshot3d(paste0("output_", runname, ".png"))
  # rgl.close()
}

radicalization_sim_df %>% 
  filter(TickNr == 100) %>% 
  select(Opinion, InactiveTicks) %>%
  ggplot(aes(x=abs(Opinion), y=InactiveTicks)) +
  geom_point(alpha=0.03)
  mutate(absOpinion = abs(Opinion)) %>% 
  select(absOpinion) -> absop
  mean(absop$absOpinion)
  
  neutralization_sim_df %>% 
    filter(TickNr == 100) %>% 
    select(AgentID,Opinion) -> NodeOps
  
  rglplot(neutralization_graph_10)




```


```{r}
xmasbatch_testrun1.1_sim_df %>% 
  filter(TickNr == 700 & ActiveState == "true" ) -> testdf

ggplot(data = testdf, aes(x=Outdegree)) +
  geom_histogram(bins = 100)

theme_set(theme_bw())

xmasbatch_testrun1.1_sim_df %>% 
  select(TickNr, Opinion, Indegree) %>% 
  filter(TickNr < 10) %>% 
  ggplot(aes(x=Opinion, y=Indegree)) + 
  geom_point(show.legend = FALSE, alpha = 0.7) -> p
  p + transition_states(TickNr, transition_length = 2, state_length = 1) -> anim
p
anim_save(animation = anim)

anim

testdf %>% 
  filter(Outdegree > 200) %>% 
  count()

testdf %>% 
  filter(Outdegree <= 20) %>% 
  count()

newtry_run1_sim_df %>% 
  filter(TickNr == 1) %>% 
  filter(Opinion == -1) %>% 
  count()

result_sim_df %>% 
  filter(Outdegree > 300) %>% 
  .[,c(1,2,3,9, 10, 11)]


  
  
```

