---
title: "analysis"
author: "Johannes Nakayama"
date: "3 12 2019"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

```

```{r}

data <- read.csv('bla2.csv')
data2 <- read.csv('bla3.csv')

```

```{r}

head(data)

```


```{r}

data %>% 
  select(TickNr, Opinion) %>% 
  group_by(TickNr) %>% 
  summarize(MeanOpinion = mean(Opinion)) %>% 
  ggplot(aes(x=TickNr, y=MeanOpinion)) +
  geom_line(color='red') + 
  theme_bw()

ggsave(filename='opinion_development.png')

```


```{r}

data %>% 
  select(TickNr, PerceivPublOpinion) %>% 
  group_by(TickNr) %>% 
  summarize(MeanPerceivPublOpinion = mean(PerceivPublOpinion)) %>% 
  ggplot(aes(x=TickNr, y=MeanPerceivPublOpinion)) +
  geom_line(color='red') + 
  theme_bw()

```


```{r}

data %>% 
  select(TickNr, Indegree) %>% 
  group_by(TickNr) %>% 
  summarize(MeanFollowers = mean(Indegree)) %>% 
  ggplot(aes(x=TickNr, y=MeanFollowers)) +
  geom_line(color='red') + 
  theme_bw()

```


```{r}

data %>% 
  filter(AgentID == 3) %>%
  ggplot(aes(x=TickNr, y=Opinion, color=ActiveStatus)) +
  geom_line() +
  theme_bw()

ggsave(filename='specific_agent_2.png')

```

```{r}

data %>% 
  filter(AgentID == 17) %>%
  ggplot(aes(x=TickNr, y=Opinion, color=ActiveStatus)) +
  geom_line() +
  theme_bw()

```

```{r}

data %>% 
  ggplot(aes(x=InclinInteract)) +
  geom_histogram(alpha=0.5, aes(y=..density..)) +
  geom_density(fill='blue', alpha=0.2) +
  theme_bw()

```

```{r}

data %>% 
  ggplot(aes(x=InclinInteract, y=Opinion)) +
  geom_point(alpha=0.2)

```



```{r}

theme_set(theme_bw())

data2$AgentID <- as.factor(data2$AgentID)

data2 %>%  
  filter(ActiveStatus == 'true') %>% 
  ggplot(aes(x=TickNr, y=Opinion, color=AgentID)) +
  geom_line(alpha=0.2) +
  theme(legend.position = "none") +
  NULL

```

